### ISSUE TITLE
Just a small comment

### ISSUE THREAD

**Issue by JForst** [Humanstate/swagger2-markdown#4]
Hi,
just stumbled over your project - nice.

Just a comment on use Moo in Markdown.pm, there is no need to use **PACKAGE**->meta->make_immutable;

see http://search.cpan.org/~haarg/Moo-2.000002/lib/Moo.pm#INCOMPATIBILITIES_WITH_MOOSE

Regards Jörg

**Comment by leejo** [comment]
Ah yeah, good point thanks! Force of habit from too much Moose before i moved to Moo :) Since it's a no-op i'll leave it in there.
